services:
  mosdns:
    image: irinesistiana/mosdns:latest
    container_name: mosdns
    hostname: mosdns
    restart: always
    networks:
      macvlan:
        ipv4_address: ${ipv4}
        ipv6_address: ${ipv6}
        mac_address: ${macaddress}
        driver_opts:
          com.docker.network.endpoint.sysctls: net.ipv6.conf.IFNAME.accept_ra_rt_info_max_plen=128

    volumes:
      - ./:/etc/mosdns/

networks:
  macvlan:
    external: true
    name: ${MACVLAN_NET}