services:
  mosdns:
    image: irinesistiana/mosdns:latest
    container_name: mosdns
    hostname: mosdns
    restart: always
    networks:
      macvlan:
        ipv4_address: ${ipv4}
        ipv6_address: ${ipv6}
        mac_address: ${macaddress}

    volumes:
      - ./:/etc/mosdns/

networks:
  macvlan:
    external: true
    name: ${MACVLAN_NET}